### ISSUE TITLE
System.NullReferenceException in Utilities\ProtoWebUtils.cs

### ISSUE THREAD

**Issue by AzimuthMiridian** [FoxCouncil/VintageHive#1]
In release 1.2.1-alpha based on 20bb110, `ProtoWebUtils.UpdateSiteLists()` currently throws a System.NullReferenceException when building the httpLinks (and later on in the method, the ftpLinks) lists, because `htmlDoc.DocumentNode.SelectNodes("//div/a");` and `htmlDoc.DocumentNode.SelectNodes("//li/a");` both return null. I'm assuming that this is because the default site the app is initially retrieving when this method is called ("http://www.inode.com" via ProtoWeb) has changed the page structure, as it seems there are no longer `div` or `li` nodes in the source for the code to iterate through.

**Comment by FoxCouncil** [comment]
It's fixed in latest commit
