### ISSUE TITLE
System.IndexOutOfRangeException in Utilities\Clients.cs

### ISSUE THREAD

**Issue by AzimuthMiridian** [FoxCouncil/VintageHive#2]
In release 1.2.1-alpha based on 20bb110, `Clients.GetGoogleArticles()` throws a System.IndexOutOfRangeException when building the `output` list on line 66, specifically caused by `Id = item.Links[0].Uri.Segments[5]` on line 68. It seems the list of segments available in the URI for this method to process has dropped to 4 from what I assume was originally a total of 6.

**Comment by FoxCouncil** [comment]
Fixed in latest commit
